name: Update the -built branch

on:
  push:
    push:
      branches:
        - master
        - gh-build

jobs:
  build-master:
    name: Built Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v4
      - name: Clear gitignore
        shell: bash
        run: rm -rf .gitignore
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'master-built'
          commit_message: 'Build master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
