name: Update the -built branch

on:
  push:
    push:
      branches:
        - master
        - develop

jobs:
  built-branch:
    name: Built Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Determine Composer cache directory
        shell: bash
        run: "echo \"COMPOSER_CACHE_DIR=$(composer config cache-dir)\" >> $GITHUB_ENV"
      - name: Cache dependencies installed with Composer
        uses: actions/cache@v2
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: os-${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            os-${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
      - uses: php-actions/composer@v4
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Clear gitignore and .github
        shell: bash
        run: |
          rm -rf .gitignore
          rm -rf .github
      - name: Push to built branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          BUILT_BRANCH: '${{ steps.extract_branch.outputs.branch }}-built'
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

          git stash

          git remote update
          git fetch --all

          # Will create branch if it does not exist
          if [[ $( git branch -r | grep "$BUILT_BRANCH" ) ]]; then
            git checkout "${BUILT_BRANCH}"
          else
            git checkout -b "${BUILT_BRANCH}"
          fi

          # Merge the former branch
          git merge - --no-edit

          rm -rf .github
          git commit -m "Merging in unbuilt branch"

          git stash pop
          git add .
          git commit -m "Adding built changes"
          git push --set-upstream origin "${BUILT_BRANCH}"
