name: Update the -built branch

on:
  push:
    push:
      branches:
        - main
        - develop
        - gh-actions

jobs:
  built-branch:
    name: Built Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clear files and install dependencies
        shell: bash
        run: |
          rm -rf vendor
          rm -rf .gitignore .github tests phpunit.xml Dockerfile docker_tag
          rm -rf output.log *.xml composer.lock
      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          composer_version: 2
          args: --prefer-dist
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to built branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILT_BRANCH: '${{ steps.extract_branch.outputs.branch }}-built'
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

          git stash
          git remote update
          git fetch --all

          # Will create branch if it does not exist
          if [[ $( git branch -r | grep "$BUILT_BRANCH" ) ]]; then
            git checkout "${BUILT_BRANCH}"
          else
            git checkout -b "${BUILT_BRANCH}"
          fi

          git reset --hard HEAD
          git stash pop

          if [ -f ".deployignore" ]; then
            rm .gitignore
            mv .deployignore .gitignore
          fi

          git rm -r --cached .
          git add .
          git commit -m "Building changes"
          git push --set-upstream origin "${INPUT_BRANCH}"
