name: Update the -built branch

on:
  push:
    push:
      branches:
        - main
        - develop
        - gh-actions

jobs:
  built-branch:
    name: Built Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          composer_version: 2
      - name: Clear files and install dependencies
        shell: bash
        run: |
          sudo rm -rf .gitignore .github tests phpunit.xml Dockerfile docker_tag
          sudo rm -rf output.log *.xml
          find . -mindepth 2 -type d -name .git | xargs rm -rf
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: '${{ steps.extract_branch.outputs.branch }}-built'
          commit_message: 'Build ${{ steps.extract_branch.outputs.branch }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
