name: Update the -built branch

on:
  push:
    push:
      branches:
        - master
        - develop
        - gh-build

jobs:
  built-branch:
    name: Built Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v4
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Clear gitignore and .github
        shell: bash
        run: |
          rm -rf .gitignore
          rm -rf .github
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: '${{ steps.extract_branch.outputs.branch }}-built'
          commit_message: 'Build ${{ steps.extract_branch.outputs.branch }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
