name: Update the -built branch

on:
  push:
    branches:
      - main
      - develop

jobs:
  built-branch:
    name: Built Branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Clear previous vendor
        shell: bash
        run: rm -rf vendor
      - name: Install dependencies
        uses: php-actions/composer@v4
        with:
          php_version: 7.4
          composer_version: 2
          args: --prefer-dist
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Push to -built branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILT_BRANCH: '${{ steps.extract_branch.outputs.branch }}-built'
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"

          rm -rf .gitignore docker_tag output.log .github
          mv .deployignore .gitignore

          git checkout -b $BUILT_BRANCH

          # git ls-files -i --exclude-from=.gitignore | xargs git rm --cached

          git add -A && git commit -m "Changes from $GITHUB_SHA"
          git push --force -u origin "${BUILT_BRANCH}"
